# Configure main menu and social menu
# ICONS --> https://tabler.io/icons
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/aleingmar?tab=repositories"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/alejandro-ingl%C3%A9s-mart%C3%ADnez-4ba726298/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "cv"
name = "cv"
url = "/CV-AlejandroInglés-18-09-24.pdf"

[social.params]
icon = "file-cv"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:inglesmartineza@gmail.com"

[social.params]
icon = "mail"